### ISSUE TITLE
We got an issue

### ISSUE THREAD

**Issue by ggore** [Mariatta/strange-relationship#156]
Use some extra emojis

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/Mariatta/strange-relationship/issues/69 (We got mo' problems), https://github.com/Mariatta/strange-relationship/issues/101 (We got a problem - Cleveland), https://github.com/Mariatta/strange-relationship/issues/143 (We got a problem :robot_face:), https://github.com/Mariatta/strange-relationship/issues/142 (We got a problem :robot_face:), and https://github.com/Mariatta/strange-relationship/issues/44 (A new serious issue).

**Comment by ggore** [comment]
adding a comment

**Comment by ggore** [comment]
closing issue

**Comment by ggore** [comment]
test reopen
